name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  autocommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README file
        run: |
          echo "$(date)" > README.md  # Adds current date to README.md

      - name: Commit changes
        run: |
          git config --global user.name 'nirajanacharya'
          git config --global user.email 'nirajan.acharya666@gmail.com'
          git add README.md
          git commit -m "Daily update [skip ci]" || echo "No changes to commit"
      
      - name: Push changes
        run: |
          git push origin HEAD
